# brew tap-new uses this file to generate an autobump workflow for the new tap
name: brew bump

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/autobump.yml
  schedule:
    # Every day at 22:15 UTC
    - cron: 15 22 * * *
  workflow_dispatch: {}

permissions: {}

defaults:
  run:
    shell: bash -xeuo pipefail {0}

jobs:
  autobump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@8f3d1ec8a696b3b9d9a6c3696b6c73033cab69e4 # 2026.08.14.1
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v7
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_committer_name: ${{ secrets.GIT_USER_NAME }}
          git_committer_email: ${{ secrets.GIT_USER_EMAIL }}
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Bump casks
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GH_TOKEN }}
          HOMEBREW_GIT_COMMITTER_NAME: ${{ secrets.GIT_USER_NAME }}
          HOMEBREW_GIT_COMMITTER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          TAP_NAME: ${{ steps.set-up-homebrew.outputs.tap-name }}
        run: brew bump --no-fork --open-pr --casks --tap="$TAP_NAME"
